/*
 * MIT License
 *
 * Copyright (c) 2020 小东
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.xclite.api.utils;

import org.ssssssss.script.MagicScript;
import org.ssssssss.script.MagicScriptContext;
import org.ssssssss.script.MagicScriptDebugContext;

import java.util.Map;

/**
 * 脚本管理
 *
 * @author mxd
 * 修改者: zhixiulee
 */
public class ScriptManager {
    /**
     * 表达式前缀
     */
    private static final String EXPRESSION_PREFIX = "/* generated by execute expression */ return ";

    /**
     * 执行脚本
     */
    public static Object executeScript(String script, MagicScriptContext context) {
        script = (context instanceof MagicScriptDebugContext ? MagicScript.DEBUG_MARK : "") + script;
        MagicScript magicScript = MagicScript.create(script, null);
        // 执行脚本
        return magicScript.execute(context);
    }

    /**
     * 执行脚本
     */
    public static Object executeExpression(String script, MagicScriptContext context) {
        return executeScript(EXPRESSION_PREFIX + script, context);
    }

    /**
     * 执行脚本
     */
    public static Object executeExpression(String script, Map<String, Object> paramMap) {
        return executeExpression(script, new MagicScriptContext(paramMap));
    }
}
